// Equipment type for each exercise — drives the illustration shown on exercise cards
export const EXERCISE_EQUIPMENT = {
  'Bench Press':            'barbell',
  'Incline Bench Press':    'barbell',
  'Decline Bench Press':    'barbell',
  'Close Grip Bench':       'barbell',
  'Dumbbell Fly':           'dumbbell',
  'Push-Ups':               'bodyweight',
  'Diamond Push-Up':        'bodyweight',
  'Weighted Dips':          'bodyweight',
  'Tricep Dip':             'bodyweight',
  'Cable Fly':              'cable',

  'Overhead Press':         'barbell',
  'Military Press':         'barbell',
  'Lateral Raise':          'dumbbell',
  'Front Raise':            'dumbbell',
  'Arnold Press':           'dumbbell',
  'Bent-Over Lateral Raise':'dumbbell',
  'Upright Row':            'barbell',
  'Face Pull':              'cable',

  'Barbell Curl':           'barbell',
  'Preacher Curl':          'barbell',
  'Dumbbell Curl':          'dumbbell',
  'Hammer Curl':            'dumbbell',
  'Concentration Curl':     'dumbbell',
  'Cable Curl':             'cable',
  'Chin-Ups':               'bodyweight',

  'Skull Crusher':          'barbell',
  'Rack Pull':              'barbell',
  'Tricep Pushdown':        'cable',
  'Overhead Extension':     'cable',
  'Kickback':               'dumbbell',

  'Crunch':                 'bodyweight',
  'Plank':                  'bodyweight',
  'Leg Raise':              'bodyweight',
  'Hanging Leg Raise':      'bodyweight',
  'Mountain Climbers':      'bodyweight',
  'Bird Dog':               'bodyweight',
  'Superman':               'bodyweight',
  'Nordic Curl':            'bodyweight',
  'Ab Wheel':               'bodyweight',
  'Russian Twist':          'bodyweight',
  'Side Plank':             'bodyweight',
  'Oblique Crunch':         'bodyweight',
  'Bicycle Crunch':         'bodyweight',
  'Cable Crunch':           'cable',
  'Wood Chop':              'cable',
  'Cable Wood Chop':        'cable',
  'Cable Kickback':         'cable',
  'Straight Arm Pulldown':  'cable',
  'Seated Cable Row':       'cable',
  'Single Arm Row':         'dumbbell',

  'Squat':                  'barbell',
  'Hack Squat':             'barbell',
  'Good Morning':           'barbell',
  'Back Extension':         'barbell',
  'Romanian Deadlift':      'barbell',
  'Stiff-Leg Deadlift':     'barbell',
  'Deadlift':               'barbell',
  'Sumo Deadlift':          'barbell',
  'Bent-Over Row':          'barbell',
  'Barbell Shrug':          'barbell',
  'Lunges':                 'barbell',
  'Bulgarian Split Squat':  'barbell',

  'Dumbbell Shrug':         'dumbbell',
  'Step-Up':                'dumbbell',

  'Leg Press':              'machine',
  'Leg Extension':          'machine',
  'Leg Curl':               'machine',
  'Lying Leg Curl':         'machine',
  'Seated Calf Raise':      'machine',

  'Lat Pulldown':           'cable',
  'Pull-Up':                'bodyweight',

  'Kettlebell Swing':       'kettlebell',

  'Hip Thrust':             'barbell',
  'Glute Bridge':           'bodyweight',

  'Standing Calf Raise':    'bodyweight',
  'Donkey Calf Raise':      'bodyweight',
  'Single-Leg Calf Raise':  'bodyweight',
  'Box Jump':               'bodyweight',
  'Jump Rope':              'bodyweight',
};
